cc2019_car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Steering Controllers ---------------------------------------
  front_left_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_front_left_steer
    pid: {p: 1.0, i: 0.1, d: 0.1}
  front_right_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_front_right_steer
    pid: {p: 1.0, i: 0.1, d: 0.1}
  rear_left_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_rear_left_steer
    pid: {p: 1.0, i: 0.1, d: 0.1}
  rear_right_steering_controller:
    type: effort_controllers/JointPositionController
    joint: chassis_to_rear_right_steer
    pid: {p: 1.0, i: 0.1, d: 0.1}

  # Velocity Controllers ---------------------------------------
  front_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_front_left_wheel
    pid: {p: 0.0, i: 0.0, d: 0.0}
  front_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_front_right_wheel
    pid: {p: 0.0, i: 0.0, d: 0.0}
  rear_left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_rear_left_wheel
    pid: {p: 0.0, i: 0.0, d: 0.0}
  rear_right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: steer_to_rear_right_wheel
    pid: {p: 0.0, i: 0.0, d: 0.0}
