cc2019_car:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Steering Controllers ---------------------------------------
  front_left_steering_controller:
    type: position_controllers/JointPositionController
    joint: chassis_to_front_left_steer
  front_right_steering_controller:
    type: position_controllers/JointPositionController
    joint: chassis_to_front_right_steer
  rear_left_steering_controller:
    type: position_controllers/JointPositionController
    joint: chassis_to_rear_left_steer
  rear_right_steering_controller:
    type: position_controllers/JointPositionController
    joint: chassis_to_rear_right_steer

  # Velocity Controllers ---------------------------------------
  front_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: steer_to_front_left_wheel
  front_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: steer_to_front_right_wheel
  rear_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: steer_to_rear_left_wheel
  rear_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: steer_to_rear_right_wheel

  # Controller Gains -------------------------------------------
  gazebo_ros_control:
    pid_gains:
      chassis_to_front_left_steer:
        p: 100
        i: 0.01
        d: 1
      chassis_to_front_right_steer:
        p: 1
        i: 0.01
        d: 0.1
      chassis_to_rear_left_steer:
        p: 1
        i: 0.01
        d: 0.1
      chassis_to_rear_right_steer:
        p: 1
        i: 0.01
        d: 0.1
      steer_to_front_left_wheel:
        p: 1
        i: 0.01
        d: 0.1
      steer_to_front_right_wheel:
        p: 1
        i: 0.01
        d: 0.1
      steer_to_rear_left_wheel:
        p: 1
        i: 0.01
        d: 0.1
      steer_to_rear_right_wheel:
        p: 1
        i: 0.01
        d: 0.1

